# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-23 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.TextField(blank=True, verbose_name='专长')),
                ('background', models.TextField(blank=True, verbose_name='教育背景')),
                ('achievements', models.TextField(blank=True, verbose_name='学术研究成果及获奖情况')),
                ('motto', models.TextField(blank=True, verbose_name='医生寄语')),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='头像')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('useridentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.UserIdentity')),
                ('department', models.CharField(choices=[('妇科', (('GYN', '妇科'),)), ('儿科', (('PAE', '小儿科'), ('NEO', '新生儿科'))), ('内科', (('PNE', '呼吸内科'), ('CAR', '心血管内科'), ('NEU', '神经内科'), ('GAS', '消化内科'), ('NEP', '肾内科'), ('END', '内分泌与代谢科'), ('RHE', '风湿免疫科'), ('HAE', '血液病科'), ('INF', '感染科'))), ('皮肤性病科', (('DER', '皮肤科'), ('STD', '性病科'))), ('营养科', (('NUT', '营养科'),)), ('骨伤科', (('SPI', '脊柱科'), ('JOI', '关节科'), ('TRA', '创伤科'))), ('男科', (('AND', '男科'),)), ('外科', (('THO', '胸外科'), ('CSG', '心脏与血管外科'), ('NSG', '神经外科'), ('HEP', '肝胆外科'), ('BUR', '烧伤科'), ('REH', '康复科'), ('URO', '泌尿外科'), ('ANO', '肛肠科'), ('GSG', '普外科'), ('TAB', '甲状腺乳腺科'))), ('肿瘤及防治科', (('IMO', '肿瘤内科'), ('TUM', '肿瘤外科'), ('RAD', '介入与放疗中心'), ('TTU', '肿瘤中医科'))), ('中医科', (('TIM', '中医内科'), ('TSG', '中医外科'), ('TGY', '中医妇科'), ('TAN', '中医男科'), ('TPE', '中医儿科'))), ('口腔颌面科', (('OAM', '口腔颌面科'),)), ('耳鼻咽喉科', (('OTO', '耳科'), ('NAS', '鼻科'), ('THR', '咽喉科'))), ('眼科', (('OPH', '眼科'),)), ('整形美容科', (('PLA', '整形美容科'),)), ('精神心理科', (('PSY', '精神科'), ('PCH', '心理科'))), ('产科', (('PLA', '产科'),)), ('报告解读科', (('CLI', '检验科'), ('RDL', '放射科'), ('ESC', '内镜科'), ('PAT', '病理科'), ('ECG', '心电图科'), ('ULT', '超声科'), ('ANE', '麻醉科'), ('MEX', '体检中心'), ('PRE', '预防保健科')))], max_length=3, verbose_name='科室')),
                ('years', models.PositiveIntegerField(verbose_name='从医时间')),
                ('title', models.CharField(choices=[('R', '住院医师'), ('A', '主治医师'), ('D', '副主任医师'), ('C', '主治医师')], max_length=1, verbose_name='职称')),
                ('ratings', models.PositiveIntegerField(default=5, verbose_name='评分')),
                ('patient_num', models.PositiveIntegerField(default=0, verbose_name='已帮助患者')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='home.Hospital', verbose_name='所属医院')),
            ],
            options={
                'verbose_name_plural': '医生',
                'verbose_name': '医生',
            },
            bases=('users.useridentity',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('useridentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.UserIdentity')),
                ('favorite_doctors', models.ManyToManyField(blank=True, to='users.Doctor')),
            ],
            options={
                'verbose_name_plural': '患者',
                'verbose_name': '患者',
            },
            bases=('users.useridentity',),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='information',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor'),
        ),
    ]
