# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='unnamed', max_length=50, verbose_name='姓名'),
        ),
    ]
