# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_doctorcomment'),
        ('users', '0004_auto_20170701_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, null=True, to='home.Post', verbose_name='收藏文章'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='favorite_doctors',
            field=models.ManyToManyField(blank=True, null=True, to='users.Doctor', verbose_name='收藏医生'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='starred_questions',
            field=models.ManyToManyField(blank=True, null=True, to='qa.Question', verbose_name='关注的问题'),
        ),
    ]
