# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20170705_1546'),
        ('users', '0005_auto_20170711_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='starred_questions',
        ),
        migrations.AlterField(
            model_name='patient',
            name='favorite_doctors',
            field=models.ManyToManyField(blank=True, to='users.Doctor', verbose_name='收藏医生'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, to='home.Post', verbose_name='收藏文章'),
        ),
        migrations.AddField(
            model_name='starredquestion',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_questions', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='starredquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question'),
        ),
    ]
