# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170711_1959'),
        ('users', '0006_auto_20170711_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='favorite_posts',
        ),
        migrations.AddField(
            model_name='favoritepost',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_posts', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='favoritepost',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post'),
        ),
    ]
