# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170711_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritepost',
            old_name='question',
            new_name='post',
        ),
    ]
