# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20170705_1546'),
        ('home', '0005_auto_20170711_1959'),
        ('users', '0008_auto_20170711_2002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritepost',
            unique_together=set([('patient', 'post')]),
        ),
        migrations.AlterUniqueTogether(
            name='starredquestion',
            unique_together=set([('patient', 'question')]),
        ),
    ]
