# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170711_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='favorite_doctors',
        ),
        migrations.AddField(
            model_name='favoritedoctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_doctors', to='users.Patient'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritedoctor',
            unique_together=set([('patient', 'doctor')]),
        ),
    ]
