# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170711_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, verbose_name='疾病历史'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未选择')], default='U', max_length=1, verbose_name='性别'),
        ),
    ]
