# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170711_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consult_price',
            field=models.FloatField(default=0, verbose_name='咨询价格'),
        ),
    ]
