# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_doctor_consult_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consult_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='咨询价格'),
        ),
    ]
