# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-16 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170712_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11, verbose_name='手机号码')),
                ('verfied', models.BooleanField(default=False, verbose_name='是否通过验证')),
                ('code', models.IntegerField(default=3011, verbose_name='验证码')),
            ],
            options={
                'verbose_name_plural': '手机号',
                'verbose_name': '手机号',
            },
        ),
    ]
