# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='verfied',
            new_name='verified',
        ),
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.IntegerField(default=7980, verbose_name='验证码'),
        ),
    ]
