# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170716_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.IntegerField(default=9729, verbose_name='验证码'),
        ),
    ]
