# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-16 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170716_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='注册时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.IntegerField(default=2945, verbose_name='验证码'),
        ),
    ]
