# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170718_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('patient_num', 'ratings', 'years'), 'verbose_name': '医生', 'verbose_name_plural': '医生'},
        ),
        migrations.AlterModelOptions(
            name='favoritedoctor',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='favoritepost',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='starredquestion',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='favoritedoctor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritepost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starredquestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritedoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor', verbose_name='医生'),
        ),
        migrations.AlterField(
            model_name='favoritedoctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_doctors', to='users.Patient', verbose_name='患者'),
        ),
        migrations.AlterField(
            model_name='favoritepost',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_posts', to='users.Patient', verbose_name='患者'),
        ),
        migrations.AlterField(
            model_name='favoritepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='starredquestion',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_questions', to='users.Patient', verbose_name='患者'),
        ),
        migrations.AlterField(
            model_name='starredquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question', verbose_name='问题'),
        ),
    ]
