# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-21 19:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20170721_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start',
            field=models.DateField(verbose_name='开始从医日期'),
        ),
        migrations.AlterField(
            model_name='information',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor', verbose_name='医生'),
        ),
    ]
