# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20170721_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/', verbose_name='医生执照'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='idcards/', verbose_name='持证自拍'),
        ),
    ]
