# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_clientid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientid',
            options={'verbose_name': '个推ID', 'verbose_name_plural': '个推ID'},
        ),
    ]
