# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20170729_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientid',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientID',
        ),
    ]
