# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20170801_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='平台总收入（元）')),
                ('gained', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已获得收入（元）')),
                ('suspended', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='未分配收入（元）')),
            ],
            options={
                'verbose_name_plural': '医生收入',
                'verbose_name': '医生收入',
                'ordering': ('suspended',),
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='wx_openid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微信openid'),
        ),
        migrations.AddField(
            model_name='income',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor', verbose_name='医生'),
        ),
    ]
