# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-16 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_auto_20170712_2237'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='咨询编号')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='users.Doctor', verbose_name='医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulations', to='users.Patient', verbose_name='患者')),
            ],
            options={
                'verbose_name_plural': '在线咨询',
                'verbose_name': '在线咨询',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.UUIDField(editable=False, verbose_name='订单编号')),
                ('cost', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='费用')),
                ('status', models.CharField(choices=[('U', '未支付'), ('P', '已支付'), ('W', '正在进行中'), ('R', '已退款'), ('F', '已完成')], default='U', editable=False, max_length=1, verbose_name='订单状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.Patient', verbose_name='顾客')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='服务类型')),
            ],
            options={
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('summary.daily.available', '每日总结'), ('summary.weekly.available', '每周总结'), ('summary.monthly.available', '每月总结')], max_length=20, verbose_name='总结类型')),
                ('charges_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='交易金额（元）')),
                ('charges_count', models.PositiveIntegerField(verbose_name='交易量（笔）')),
                ('summary_from', models.DateTimeField(verbose_name='统计起始时间')),
                ('summary_to', models.DateTimeField(verbose_name='统计终止时间')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
