# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_auto_20170712_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='咨询单号')),
                ('status', models.CharField(choices=[('U', '未支付'), ('P', '已支付'), ('W', '正在进行中'), ('F', '已完成')], default='U', max_length=1, verbose_name='状态')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='users.Doctor', verbose_name='医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulations', to='users.Patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '在线咨询',
                'verbose_name_plural': '在线咨询',
            },
        ),
    ]
