# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ('-created',), 'verbose_name': '在线咨询', 'verbose_name_plural': '在线咨询'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ('-created',), 'verbose_name': '交易总结', 'verbose_name_plural': '交易总结'},
        ),
        migrations.AddField(
            model_name='consultation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
