# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170718_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='start',
            field=models.DateTimeField(auto_now=True, verbose_name='开始时间'),
        ),
    ]
