# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170712_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default='623b6d1abbe44819945ba86a8c90b525', editable=False, primary_key=True, serialize=False, verbose_name='咨询单号'),
        ),
    ]
