# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0003_auto_20170713_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.UUIDField(default='05dcc68a702847618cbc737bf0431080', editable=False, verbose_name='订单编号')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='费用')),
                ('status', models.CharField(choices=[('U', '未支付'), ('P', '已支付'), ('W', '正在进行中'), ('R', '已退款'), ('F', '已完成')], default='U', max_length=1, verbose_name='订单状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='服务类型')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='status',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
