# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20170801_1506'),
        ('services', '0003_consultation_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.Doctor', verbose_name='服务提供者'),
            preserve_default=False,
        ),
    ]
