# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 11:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20170801_1506'),
        ('services', '0004_order_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField(default=False, verbose_name='匿名回答')),
                ('ratings', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Doctor', verbose_name='全部评价')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Order', verbose_name='评价订单')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Patient', verbose_name='全部评价')),
            ],
            options={
                'verbose_name': '订单评论',
                'verbose_name_plural': '订单评论',
            },
        ),
    ]
