# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170713_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default='b020e66e7880475690c481b9bd55061f', primary_key=True, serialize=False, verbose_name='咨询编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(default='bf21147de4024fc4bb5c3ac851d7f2b4', editable=False, verbose_name='订单编号'),
        ),
    ]
