# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20170713_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='交易金额（元）')),
                ('charges_count', models.PositiveIntegerField(verbose_name='交易量（笔）')),
                ('summary_from', models.DateTimeField(verbose_name='统计起始时间')),
                ('summary_to', models.DateTimeField(verbose_name='统计终止时间')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='咨询编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(editable=False, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('U', '未支付'), ('P', '已支付'), ('W', '正在进行中'), ('R', '已退款'), ('F', '已完成')], default='U', editable=False, max_length=1, verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('summary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Summary')),
            ],
            bases=('services.summary',),
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('summary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Summary')),
            ],
            bases=('services.summary',),
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('summary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.Summary')),
            ],
            bases=('services.summary',),
        ),
    ]
