# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Doctor', verbose_name='医生'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Patient', verbose_name='患者'),
        ),
    ]
