# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170712_2237'),
        ('services', '0007_auto_20170714_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.Patient', verbose_name='顾客'),
            preserve_default=False,
        ),
    ]
