# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20170801_1506'),
        ('services', '0008_auto_20170808_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='会员编号')),
                ('expire', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='charge_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='收款编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.Doctor', verbose_name='服务提供者'),
        ),
    ]
