# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20170809_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='id_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='会员姓名'),
        ),
    ]
