# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20170627_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='patient',
            new_name='questioner',
        ),
    ]
