# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('qa', '0005_questionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replier_id', models.PositiveIntegerField(blank=True, null=True)),
                ('body', models.TextField(verbose_name='评论内容')),
                ('upvotes', models.PositiveIntegerField(default=0, verbose_name='获赞数')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('replier_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='qa.AnswerComment')),
            ],
            options={
                'verbose_name': '回答评论',
                'verbose_name_plural': '回答评论',
            },
        ),
    ]
