# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_answercomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercomment',
            options={'ordering': ('-created',), 'verbose_name': '回答评论', 'verbose_name_plural': '回答评论'},
        ),
        migrations.AddField(
            model_name='answercomment',
            name='answer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qa.Answer'),
            preserve_default=False,
        ),
    ]
