# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_auto_20170705_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qa.Answer', verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='replier_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='回答者编号'),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='replier_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='回答者身份'),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='qa.AnswerComment', verbose_name='回复评论'),
        ),
    ]
