# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20170705_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.Patient', verbose_name='提问者'),
        ),
    ]
