# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_auto_20170711_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questioner',
            new_name='owner',
        ),
    ]
