# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_auto_20170714_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
