# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_auto_20170715_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('picked', 'upvotes', '-created'), 'verbose_name': '回答', 'verbose_name_plural': '回答'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('stars', 'answers', '-updated'), 'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
    ]
