# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-11 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20170801_1506'),
        ('qa', '0014_auto_20170721_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Doctor', verbose_name='回答医生'),
        ),
    ]
