# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('doctor_num', models.IntegerField(verbose_name='医生人数')),
                ('rank', models.CharField(choices=[('3A', '三级甲等'), ('3B', '三级乙等'), ('3C', '三级丙等'), ('2A', '二级甲等'), ('2B', '二级乙等'), ('2C', '二级丙等'), ('1A', '一级甲等'), ('1B', '一级乙等'), ('1C', '一级丙等')], max_length=10, verbose_name='医院等级')),
                ('phone', models.IntegerField(verbose_name='电话')),
                ('description', models.TextField(blank=True, verbose_name='医院介绍')),
                ('photo', models.ImageField(blank=True, upload_to='hospitals/', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '医院',
                'verbose_name': '医院',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('photo', models.ImageField(upload_to='posts/', verbose_name='图片')),
                ('body', models.TextField(verbose_name='正文')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
                'ordering': ('-created',),
            },
        ),
    ]
