# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-27 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_hospital_doctor_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='图片'),
        ),
    ]
