# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 21:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170711_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcomment',
            name='ratings',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='评分'),
        ),
    ]
