# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('home', '0006_auto_20170713_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcomment',
            name='order_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Order', verbose_name='订单编号'),
        ),
    ]
