# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170718_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctor_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='医生人数'),
        ),
    ]
