# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-02 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170802_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorcomment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorcomment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='doctorcomment',
            name='patient',
        ),
        migrations.DeleteModel(
            name='DoctorComment',
        ),
    ]
